---
# Service DNS will be "clickstream-blue-hazelcast.default.svc.cluster.local".
---
# $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
# $$$$$$$$$$$$$$$$$$$$$ SERVICE DEFINITIONS $$$$$$$$$$$$$$$$$$$$$
# $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
---
apiVersion: v1
kind: Service
metadata:
  name: clickstream-blue-hazelcast
spec:
  clusterIP: None
  selector:
    app: clickstream-blue-hazelcast
  ports:
  - port: 5701
---
