---
# OPTIONAL
# OPTIONAL
# OPTIONAL - If not running on HZ Cloud, to run Management Center
# OPTIONAL
# OPTIONAL
---
# Service DNS will be "trade-monitor-mancenter.default.svc.cluster.local".
---
# Management Center
---
apiVersion: v1
kind: Service
metadata:
  name: trade-monitor-management-center
spec:
  selector:
    app: trade-monitor-management-center
  ports:
    - name: trade-monitor-management-center
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
# Only need 1 management-center
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trade-monitor-management-center
spec:
  selector:
    matchLabels:
      app: trade-monitor-management-center
  template:
    metadata:
      labels:
        app: trade-monitor-management-center
    spec:
      containers:
        - image: "hazelcast-platform-demos/trade-monitor-management-center"
          imagePullPolicy: Never
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
          name: trade-monitor-management-center-container
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 30
---
